cerad_app:
    resource: "@CeradAppBundle/Resources/config/routing.yml"
    prefix:   /
    
logout:
    pattern: /logout
    
cerad_user:
    resource: "@CeradUserBundle/Resources/config/routing/oauth.yml"
    prefix:   /
