cerad_app:
    resource: "@CeradAppBundle/Resources/config/routing.yml"
    prefix:   /

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login
    
# These are needed even though security.yml spells out the pattern
facebook_login:
    pattern: /login/check-facebook

google_login:
    pattern: /login/check-google
    
google_connect:
    pattern: /connect/google

custom_login:
    pattern: /login/check-custom

github_login:
    pattern: /login/check-github
    
github_connect:
    pattern: /connect/github
    
logout:
    pattern: /logout
