security:
    providers:
        in_memory:
            memory: ~
        hwi:                               
            id: hwi_oauth.user.provider
        
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

       #default:
       #    anonymous: ~
            
        secured_area:
            pattern: ^/
            anonymous: ~
            logout:
                path:   /logout
                target: /
                   
            oauth:
                resource_owners:
                   #facebook:           "/login/check-facebook"
                    google:             "/login/check-google"
                   #my_custom_provider: "/login/check-custom"
                    github:             "/login/check-github"
                login_path:        /login
                use_forward:       false
                failure_path:      /login
                
                oauth_user_provider:
                    service: hwi_oauth.user.provider
                   
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        